### ISSUE TITLE
Review of concepts

### ISSUE THREAD

**Issue by manuparra** [manuparra/ska-serverless#4]
HPC: 
- Fields: HEP, Bio, Astro, IA, Climate, Simulation, Modelling, MonteCarlo, ...
- Mngt. Services: Slurm, HT-Condor, OCGE, ...
- Example: DNA seq, Pi, ...

**Comment by manuparra** [comment]
Cloud Computing:
- IAA -> OpenStack (IaaS) (OpenSource) Development: DevStack (development use)
  - IaaS, PaaS, SaaS 
  - IaaS: OpenStack, OpenNebula, Eucaliptus,...
  - PaaS: ...
  - SaaS: GDocs, OwnCloud, Jupyter Notebooks...

**Comment by manuparra** [comment]
Container: 
- Not 100% isolated
- Flexible
- Reproducible

**Comment by manuparra** [comment]
Containers:
- Where are my apps/services:
  - https://hub.docker.com/
  
Example:

- Install docker first:

``docker pull matpower/octave``
``docker run -it --rm matpower/octave:latest octave-cli``
``docker run -it -v /tmp/:/data/ --rm matpower/octave:latest octave-cli /data/filtering.8c``

Example with Jupyter:
``docker run -p 8888:8888 jupyter/scipy-notebook``

**Comment by carlosrm9** [comment]
I have questions on how to manage creation of new files to run Octave (or other program) from a Docker Container. I am also interested in knowing if Docker conteiners could be run using a GUI or they are only available to use from the terminal (I suppose it will depend on the container).  I also don't understand well all the flags used in the commands above.

**Comment by manuparra** [comment]
Thank you Carlos, good questions.

For this example with OCTAVE, you can create files inside the container or outside the container (in your system).
You can create files inside by using `docker exec <name of the container> /bin/bash` with this command you enter into the container and in this moment you can create files, with vim, emacs, etc. (if installed). The second option is to mount your local files inside the container, in this case, you have to create the container using `-v LocalPath:ContainerPath` for example: `docker run -it -v /tmp/:/data/ --rm matpower/octave:latest octave-cli /data/filtering.8c`.

In both cases you want to execute a container that was created to execute OCTAVE, but probably you want to execute other things (python, jupyter, etc.) In these cases you have to look for a container that have this functionality or you have to create from the scratch.

Yes you can execute things that have a GUI, like regular applications with windows, etc. but you have suppport  for X windows. If your are in Ubuntu as host system it will work perfectly, but in windows, you have to install support for X.

**Comment by manuparra** [comment]
Regarding the flags:
- please read the next: https://docs.docker.com/engine/reference/commandline/run/
