### ISSUE TITLE
update to wsclean version 3

### ISSUE THREAD

**Issue by jmoldon** [manuparra/ska-serverless#7]
This is not critical at the moment, but it would be good to reconcile the versions at some point, so older wsclean versions are not perpetuated in the future (since some functionality and parameters are different).

Currently you are installing version from stimela: `stimela/wsclean:1.6.3`, which is v2.9, downloaded from dockerhub. That is fine for early tests and development, but at some point v3 (e.g. 3.10) should be used. Docker definition files are available here: https://gitlab.com/aroffringa/wsclean/-/tree/master/scripts/docker

stimela version offers standard compilations, while those docker files include additions like idg or everybeam that gives more flexibility. Also, it allows GPU usage, which will be relevant in the future.

Doing this soonish will avoid having to refactor code in the future.

**Comment by manuparra** [comment]
Yes, we want to review it @jmoldon .

**Comment by carlosrm9** [comment]
Updated to v3.2
