### ISSUE TITLE
Explore ddfacet

### ISSUE THREAD

**Issue by manuparra** [manuparra/ska-serverless#9]
Example of execution:

`kMS.py --MSName [proxima_20210321_split.ms](http://proxima_20210321_split.ms/) --SolverType CohJones --PolMode Scalar --OutSolsName testcohjones --InCol DATA --OutCol CORRDATA --SkyModelCol PREDICT_DDF --dt 5 --NChanSols 1  --MaxFacetSize 0.5 --MinFacetSize 0.1 --ApplyToDir 0`

To execute directly:
`chmod a+x kMS.py`
`kMS.py`

Indirect:

`python /..../kMS.py`

**Comment by carlosrm9** [comment]
Done!
